In [ ]:
import pandas as pd 
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#reading the data

df = pd.read_excel("/content/drive/MyDrive/do well/week 2/week_2_data.xlsx")
df.head()
# to check the frist 5 rows of the dataset

Weeks W1 Unnamed: 2 Unnamed: 3  ... Unnamed: 7 Unnamed: 8 Unnamed: 9 Unnamed: 10
0  Days  M          T          W  ...          T          W         TH           F
1     1  4          5          5  ...          2          3          4           5
2     2  1          2          3  ...          5          6          6           7
3     3  3          4          5  ...          3          4          5           6
4     4  1          2          3  ...          2          3          4           5

[5 rows x 11 columns]

In [ ]:
df.shape
# to check the shape of the dataset

(1001, 11)

In [ ]:
# reading the last 5 rows of the data set
df.tail()

Weeks W1 Unnamed: 2  ... Unnamed: 8 Unnamed: 9 Unnamed: 10
996    996  2          3  ...          3          3           3
997    997  5          5  ...          3          4         NaN
998    998  1          1  ...          4          5           5
999    999  1          1  ...          2          2         NaN
1000  1000  2          2  ...          3          4           4

[5 rows x 11 columns]

In [ ]:
#to describe the data
df.describe()

Weeks    W1  Unnamed: 2  ...  Unnamed: 8  Unnamed: 9  Unnamed: 10
count    1001  1001        1001  ...         835         848          839
unique   1001     6           6  ...           7           7            7
top       840     5           5  ...           6           6            7
freq        1   222         393  ...         262         410          381

[4 rows x 11 columns]

In [ ]:
#checking the names of the columns
df.columns

Index(['Weeks', 'W1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5',
       'W2', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10'],
      dtype='object')

In [ ]:
#to rename the names of columns

data = df.rename(columns = {'Weeks': "Weeks", 'W1' : "W1M", 'Unnamed: 2' : "W1T", 'Unnamed: 3': "W1W", 'Unnamed: 4': "W1Th", 'Unnamed: 5':"W1F",
       'W2': "W2M", 'Unnamed: 7':'W2T', 'Unnamed: 8':"W2W", 'Unnamed: 9':"W2Th", 'Unnamed: 10': "W2F"})

In [ ]:

data =  data.drop("Weeks", axis = 1 ) # dropping the column ("Weeks")
data = data.drop([0]) # droping the first row (days)

In [ ]:
data.head()

W1M W1T W1W W1Th W1F  W2M W2T W2W W2Th  W2F
1   4   5   5    6   7    1   2   3    4    5
2   1   2   3    4   5    5   5   6    6    7
3   3   4   5    6   7  NaN   3   4    5    6
4   1   2   3    4   5  NaN   2   3    4    5
5   2   3   4    5   6    5   5   6    6  NaN

In [ ]:
data.shape # checking the shape of modified data

(1000, 10)

In [ ]:
data.to_csv("/content/drive/MyDrive/do well/week 2/week_2_data.csv") # saving it to csv form

In [ ]:
data.describe() # #Display some descriptive statistics for the  columns

W1M   W1T   W1W  W1Th   W1F  W2M  W2T  W2W  W2Th  W2F
count   1000  1000  1000  1000  1000  792  799  834   847  838
unique     5     5     5     6     7    5    5    6     6    6
top        5     5     5     6     7    1    5    6     6    7
freq     222   393   563   509   489  180  278  262   410  381

In [ ]:
#information of the data set
data.info()#checking for null values too.

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 1 to 1000
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   W1M     1000 non-null   object
 1   W1T     1000 non-null   object
 2   W1W     1000 non-null   object
 3   W1Th    1000 non-null   object
 4   W1F     1000 non-null   object
 5   W2M     792 non-null    object
 6   W2T     799 non-null    object
 7   W2W     834 non-null    object
 8   W2Th    847 non-null    object
 9   W2F     838 non-null    object
dtypes: object(10)
memory usage: 85.9+ KB


##### we have observed that the data type is of object that should we int form so now we will convert the datatype in int

In [ ]:
for i in data.columns:
  data[i] = data[i].astype(float)  # converting the datatype into float

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 1 to 1000
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   W1M     1000 non-null   float64
 1   W1T     1000 non-null   float64
 2   W1W     1000 non-null   float64
 3   W1Th    1000 non-null   float64
 4   W1F     1000 non-null   float64
 5   W2M     792 non-null    float64
 6   W2T     799 non-null    float64
 7   W2W     834 non-null    float64
 8   W2Th    847 non-null    float64
 9   W2F     838 non-null    float64
dtypes: float64(10)
memory usage: 85.9 KB


In [ ]:
data.describe() #basic statistic computation of the data

W1M          W1T  ...        W2Th         W2F
count  1000.000000  1000.000000  ...  847.000000  838.000000
mean      3.075000     3.739000  ...    5.101535    5.943914
std       1.424572     1.230607  ...    1.050311    1.191549
min       1.000000     1.000000  ...    1.000000    2.000000
25%       2.000000     3.000000  ...    4.000000    5.000000
50%       3.000000     4.000000  ...    5.000000    6.000000
75%       4.000000     5.000000  ...    6.000000    7.000000
max       5.000000     5.000000  ...    6.000000    7.000000

[8 rows x 10 columns]

#### I have observed that most of the data is filled sequentially 
- for a particular week and row
- it is filled like that
 - 2,3,4,5,6
 - 3,3,4,4,5,5
 - 2,2,3,4,4

- and is filled in asscending order for the particular week.

- so we will deal with imputing missing values according to that.

In [ ]:
data #inpecting the data again

W1M  W1T  W1W  W1Th  W1F  W2M  W2T  W2W  W2Th  W2F
1     4.0  5.0  5.0   6.0  7.0  1.0  2.0  3.0   4.0  5.0
2     1.0  2.0  3.0   4.0  5.0  5.0  5.0  6.0   6.0  7.0
3     3.0  4.0  5.0   6.0  7.0  NaN  3.0  4.0   5.0  6.0
4     1.0  2.0  3.0   4.0  5.0  NaN  2.0  3.0   4.0  5.0
5     2.0  3.0  4.0   5.0  6.0  5.0  5.0  6.0   6.0  NaN
...   ...  ...  ...   ...  ...  ...  ...  ...   ...  ...
996   2.0  3.0  4.0   5.0  5.0  1.0  2.0  3.0   3.0  3.0
997   5.0  5.0  5.0   5.0  7.0  2.0  2.0  3.0   4.0  NaN
998   1.0  1.0  1.0   2.0  3.0  4.0  NaN  4.0   5.0  5.0
999   1.0  1.0  2.0   2.0  3.0  NaN  1.0  2.0   2.0  NaN
1000  2.0  2.0  2.0   2.0  3.0  NaN  2.0  3.0   4.0  4.0

[1000 rows x 10 columns]

In [ ]:
data_week_2 = data[data.columns[5:10]]
data_week_1 = data[data.columns[0:5]]

In [ ]:
data_week_2

W2M  W2T  W2W  W2Th  W2F
1     1.0  2.0  3.0   4.0  5.0
2     5.0  5.0  6.0   6.0  7.0
3     NaN  3.0  4.0   5.0  6.0
4     NaN  2.0  3.0   4.0  5.0
5     5.0  5.0  6.0   6.0  NaN
...   ...  ...  ...   ...  ...
996   1.0  2.0  3.0   3.0  3.0
997   2.0  2.0  3.0   4.0  NaN
998   4.0  NaN  4.0   5.0  5.0
999   NaN  1.0  2.0   2.0  NaN
1000  NaN  2.0  3.0   4.0  4.0

[1000 rows x 5 columns]

In [ ]:
# how many missing values present in the data?
data_week_2.isnull().sum()

W2M     208
W2T     201
W2W     166
W2Th    153
W2F     162
dtype: int64

In [ ]:
data_week_2.shape[1]

1000

### Treatment with missing values

- After observing the data we find that the missing number of data points to include closer to the missing value
-  so we use KNN imputer 

In [ ]:
# import the KNNimputer class 
from sklearn.impute import KNNImputer 
# create an object for KNNImputer 
imputer = KNNImputer(n_neighbors=2) 
After_imputation = imputer.fit_transform(data_week_2) 

In [ ]:
print(After_imputation)

[[1. 2. 3. 4. 5.]
 [5. 5. 6. 6. 7.]
 [2. 3. 4. 5. 6.]
 ...
 [4. 3. 4. 5. 5.]
 [1. 1. 2. 2. 2.]
 [1. 2. 3. 4. 4.]]


In [ ]:
data_week_2_imputed = pd.DataFrame(data = After_imputation,columns=["W2M", "W2T","W2W", "W2Th", "W2F"] )

In [ ]:
data_week_2_imputed

W2M  W2T  W2W  W2Th  W2F
0    1.0  2.0  3.0   4.0  5.0
1    5.0  5.0  6.0   6.0  7.0
2    2.0  3.0  4.0   5.0  6.0
3    1.0  2.0  3.0   4.0  5.0
4    5.0  5.0  6.0   6.0  7.0
..   ...  ...  ...   ...  ...
995  1.0  2.0  3.0   3.0  3.0
996  2.0  2.0  3.0   4.0  5.0
997  4.0  3.0  4.0   5.0  5.0
998  1.0  1.0  2.0   2.0  2.0
999  1.0  2.0  3.0   4.0  4.0

[1000 rows x 5 columns]

In [ ]:
data_imputed = data_week_1.join(data_week_2_imputed)
data_imputed

W1M  W1T  W1W  W1Th  W1F  W2M  W2T  W2W  W2Th  W2F
0    4.0  5.0  5.0   6.0  7.0  1.0  2.0  3.0   4.0  5.0
1    1.0  2.0  3.0   4.0  5.0  5.0  5.0  6.0   6.0  7.0
2    3.0  4.0  5.0   6.0  7.0  2.0  3.0  4.0   5.0  6.0
3    1.0  2.0  3.0   4.0  5.0  1.0  2.0  3.0   4.0  5.0
4    2.0  3.0  4.0   5.0  6.0  5.0  5.0  6.0   6.0  7.0
..   ...  ...  ...   ...  ...  ...  ...  ...   ...  ...
995  2.0  3.0  4.0   5.0  5.0  1.0  2.0  3.0   3.0  3.0
996  5.0  5.0  5.0   5.0  7.0  2.0  2.0  3.0   4.0  5.0
997  1.0  1.0  1.0   2.0  3.0  4.0  3.0  4.0   5.0  5.0
998  1.0  1.0  2.0   2.0  3.0  1.0  1.0  2.0   2.0  2.0
999  2.0  2.0  2.0   2.0  3.0  1.0  2.0  3.0   4.0  4.0

[1000 rows x 10 columns]

In [ ]:
data_imputed.to_csv("/content/drive/MyDrive/do well/week 2/week_2_imputed.csv")

In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/do well/week 2/final_data.csv")
print(df.shape)
df.head()

In [ ]:
from sklearn.model_selection import train_test_split
train , test = train_test_split(df, test_size = 0.5)

x_train = train.drop('Unnamed: 0', axis=1)
y_train = train['W']

x_test = test.drop('Unnamed: 0', axis = 1)
y_test = test['W']

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))

x_train_scaled = scaler.fit_transform(x_train)
x_train = pd.DataFrame(x_train_scaled)

x_test_scaled = scaler.fit_transform(x_test)
x_test = pd.DataFrame(x_test_scaled)

In [ ]:
#import required packages
from sklearn import neighbors
from sklearn.metrics import mean_squared_error 
from math import sqrt
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
rmse_val = [] #to store rmse values for different k
for K in range(20):
    K = K+1
    model = neighbors.KNeighborsRegressor(n_neighbors = K)

    model.fit(x_train, y_train)  #fit the model
    pred=model.predict(x_test) #make prediction on test set
    error = sqrt(mean_squared_error(y_test,pred)) #calculate rmse
    rmse_val.append(error) #store rmse values
    print('RMSE value for k= ' , K , 'is:', error)

In [ ]:
#plotting the rmse values against k values
curve = pd.DataFrame(rmse_val)  
curve.plot()

In [ ]:
dd = pd.read_csv("/content/drive/MyDrive/do well/week 2/final_data.csv")
dd = dd.drop(dd.index[600:2000])
dd = dd.drop("Unnamed: 0", axis = 1)

In [ ]:
dd.to_csv("/content/drive/MyDrive/do well/sample_data.csv")

In [ ]:
train = train.drop("Unnamed: 0", axis =1)

In [ ]:
#reading test and submission files
test = pd.DataFrame(x_test_scaled)
submission = dd
submission['M'] = test[0]
submission['T'] = test[1]

In [ ]:
#preprocessing test dataset
#test.drop(['Item_Identifier', 'Outlet_Identifier'], axis=1, inplace=True)
#test['Item_Weight'].fillna(mean, inplace =True)
test = pd.get_dummies(test)
test_scaled = scaler.fit_transform(test)
test = pd.DataFrame(test_scaled)

In [ ]:
#predicting on the test set and creating submission file
predict = model.predict(test)
submission['M'] = predict
submission["T"] = predict
submission['W'] = predict
submission["TH"] = predict
submission['F'] = predict
submission.to_csv('/content/drive/MyDrive/do well/predicted.csv',index=False)

In [ ]:
train.shape
train = train.drop(train.index[600:1400])

In [ ]:
#predicting on the test set and creating submission file
predict = model.predict(train)
submission['M'] = predict
submission["T"] = predict
submission['W'] = predict
submission["TH"] = predict
submission['F'] = predict
submission.to_csv('/content/drive/MyDrive/do well/predicted_with_train.csv',index=False)

In [ ]:
from sklearn.model_selection import GridSearchCV
params = {'n_neighbors':[2,3,4,5,6]}

knn = neighbors.KNeighborsRegressor()

model = GridSearchCV(knn, params, cv=5)
model.fit(x_train,y_train)
model.best_params_